# ================== PostgreSQL ==================
spring.datasource.url=jdbc:postgresql://localhost:5431/Scouts
spring.datasource.username=postgres
spring.datasource.password=Pswd-(19AA57

# ================== Flyway ==================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=false

# ================== JPA ==================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.envers.autoRegisterListeners=false

# ================== JWT ==================
jwt.secret=i_am_so_lonely_all_the_other_viltrumites_are_scared_of_me_no_one_talks_to_me