CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(50)                             NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    role          VARCHAR(30)                             NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);