CREATE TABLE teams
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description TEXT,
    status      VARCHAR(20)                             NOT NULL DEFAULT 'ACTIVE',
    leader_id   BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

CREATE TABLE scouts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(100)                            NOT NULL,
    team_id        BIGINT                                  NOT NULL,
    joined_at      date,
    rank           VARCHAR(50)                             NOT NULL DEFAULT 'MEMBER',
    position       VARCHAR(100),
    total_missions INTEGER                                 NOT NULL DEFAULT 0,
    status         VARCHAR(50)                             NOT NULL DEFAULT 'ACTIVE',
    notes          TEXT,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_scouts PRIMARY KEY (id)
);

ALTER TABLE scouts
    ADD CONSTRAINT FK_SCOUTS_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE teams
    ADD CONSTRAINT FK_TEAMS_ON_LEADER FOREIGN KEY (leader_id) REFERENCES scouts (id);