CREATE TABLE operations
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type                       VARCHAR(50)                             NOT NULL DEFAULT 'MISSION',
    title                      VARCHAR(255)                            NOT NULL,
    description                TEXT,
    priority                   INTEGER                                 NOT NULL DEFAULT 3,
    start_datetime             TIMESTAMP WITHOUT TIME ZONE,
    end_datetime               TIMESTAMP WITHOUT TIME ZONE,
    planned_participants_count INTEGER                                 NOT NULL DEFAULT 0,
    actual_participants_count  INTEGER                                 NOT NULL DEFAULT 0,
    status                     VARCHAR(30)                             NOT NULL DEFAULT 'PLANNED',
    notes                      TEXT,
    created_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_operations PRIMARY KEY (id),
    CONSTRAINT chk_operations_priority CHECK (priority BETWEEN 1 AND 5)
);

CREATE TABLE participations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    operation_id  BIGINT,
    scout_id      BIGINT,
    result_status VARCHAR(50)                             NOT NULL DEFAULT 'ACTIVE',
    notes         TEXT,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_participations PRIMARY KEY (id),
    CONSTRAINT uk_participation UNIQUE (operation_id, scout_id)
);

ALTER TABLE participations
    ADD CONSTRAINT FK_PARTICIPATIONS_ON_OPERATION FOREIGN KEY (operation_id) REFERENCES operations (id);

ALTER TABLE participations
    ADD CONSTRAINT FK_PARTICIPATIONS_ON_SCOUT FOREIGN KEY (scout_id) REFERENCES scouts (id);